### ISSUE TITLE
Add `EntityDef.cleanup`

### ISSUE THREAD

**Issue by Hexcede** [SaveFileLost/Arc#5]
Add an `EntityDef.cleanup` definition.

**Comment by Weldify** [comment]
Implemented.
`cleanup` will only get called on authority, i.e. if the entity originates from the server and was removed on the server, or if the entity originates from the client and is removed on the client.
Also added `clientSpawn` and `clientDelete` methods. The former is called when the entity is first replicated, the latter is called when the server replicates its deletion.
